name: Docker Build and Push

on:
  push:
    branches:
      - main  # ou la branche de ton choix
  pull_request:
    branches:
      - main  # ou la branche de ton choix

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout du code
      - name: Checkout code
        uses: actions/checkout@v2

      # Configuration de Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Connexion à Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Construire l'image Docker
      - name: Build Docker image
        run: |
          docker build -t ishimwe076/my-app:v2.0 .
      # Pousser l'image sur Docker Hub
      - name: Push Docker image
        run: |
          docker push ishimwe076/my-app:v2.0
